#ErsatzTV-Filler-Theme
#Theme Name: light
#Creator: liam8888999

#desired background colour around image can be set to random for a random colour to be generated for each video
backgroundcolour=white

#set background colour for news - can be set to random
newsbackgroundcolour=white

#set text colour for news - can be set to random
newstextcolour=black

#set colours for channel currently offline filler
offlinebackgroundcolour=white
offlinetextcolour=black
