#ErsatzTV-Filler-Theme
#Theme Name: candycane
#Creator: liam8888999

#desired background colour around image can be set to random for a random colour to be generated for each video
backgroundcolour=red

#set background colour for news - can be set to random
newsbackgroundcolour=red

#set text colour for news - can be set to random
newstextcolour=white

#set colours for channel currently offline filler
offlinebackgroundcolour=red
offlinetextcolour=white
