#ErsatzTV-Filler-Theme
#Theme Name: stopandgo
#Creator: liam8888999

#desired background colour around image can be set to random for a random colour to be generated for each video
backgroundcolour=lightgreen

#set background colour for news - can be set to random
newsbackgroundcolour=lightgreen

#set text colour for news - can be set to random
newstextcolour=red

#set colours for channel currently offline filler
offlinebackgroundcolour=lightgreen
offlinetextcolour=red
